version: '3.8'

services:
  web:
    image: nginx:latest
    ports:
      - "8080:80"

    volumes:
      - .:/app
    environment:
      - FLASK_APP=src/app.py
      - FLASK_ENV=development
      - OPENAI_API_KEY=${OPENAI_API_KEY}
    command: flask run --host=0.0.0.0
